### ISSUE TITLE
Question: Docker-compose for easy testing

### ISSUE THREAD

**Issue by ppaslan** [SSHcom/privx-kube#58]
Saw this section in the deployments.yaml file inside this chart, does this mean there is a way
to deploy this on say docker by using something like docker-compose?

This would be helpful in situations where one might want to have a quick way to deploy a PrivX instance on docker in order to test something like a script or an application which uses PrivX.

```yaml
env:
  - name: IS_DOCKER_ENV
    value: "yes"
  - name: KUBERNETES_MODE
    value: "true"
```
